package:
  version: 1.1.0
  url: https://github.com/pooza/shooby-do-bop
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
cert:
  url: https://curl.haxx.se/ca/cacert.pem
youtube:
  urls:
    videos: https://www.googleapis.com/youtube/v3/videos
hashtags: []
slack:
  hooks: []
