package:
  version: 2.0.0
  url: https://github.com/pooza/shooby-do-bop
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
youtube:
  urls:
    videos: https://www.googleapis.com/youtube/v3/videos
