package:
  version: 2.2.1
  url: https://github.com/pooza/shooby-do-bop
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
youtube:
  url: https://www.googleapis.com/
http:
  retry:
    limit: 3
    seconds: 1
